apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: game-2048
  labels:
    app: game-2048
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game-2048
  serviceName: game-2048-service
  template:
    metadata:
      labels:
        app: game-2048
    spec:
      containers:
        - name: game-2048
          image: runseb/2048:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: game-data
              mountPath: /usr/share/nginx/html  # Example path for persistent data
  volumeClaimTemplates:
    - metadata:
        name: game-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
