apiVersion: v1
kind: PersistentVolume
metadata:
  name: game-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/game-2048  # Path on the node
